### consultar todas las peliculas
GET http://localhost:3000/movies

### consultar una pelicula por id
GET http://localhost:3000/movies/12345

### crear
POST http://localhost:3000/movies
Content-Type:   application/json

{
    "title": "The Matrix",
    "director": "Lana Wachowski, Lilly Wachowski",
    "posterUrl": "https://m.media-amazon.com/images/I/51EG732BV3L.jpg",
    "releaseYear": 1999,
    "genre": [
        "Science Fiction",
        "Action"
    ]
}

### eliminar
DELETE http://localhost:3000/movies/

### actualizar
PUT http://localhost:3000/movies/20