### consultar todas las peliculas
GET http://localhost:3000/movies


### consultar una pelicula por id
GET http://localhost:3000/movies/a5764f7c-49c0-42d0-8e4a-58bb9d60e869

### crear
POST http://localhost:3000/movies
Content-Type:   application/json

{
    "title": "The Matrix Recargado",
    "director": [2,3],
    "posterUrl": "https://m.media-amazon.com/images/I/51EG732BV3L.jpg",
    "genre": [
        1,2
    ]
}

### eliminar
DELETE http://localhost:3000/movies/1234

### actualizar
PUT http://localhost:3000/movies/20
Content-Type:   application/json

{
    "posterUrl": "https://m.media-amazon.com/images/I/51EG732BV3L.jpg"
}
